# Fixed dataset path
dataset_path: ImagenetHighResolution

# Fixed model settings
device: cuda
epochs: 1
canvas_size: 512

# Sweep dimensions
batch_size: 32

lr: 0.0003

min_lr: 0.00001
weight_decay: 0.001

# Optional W&B logging. Set both values to enable logging.
project: null
entity: null
